### ISSUE TITLE
hook plugin is broken

### ISSUE THREAD

**Issue by GamingGav** [oceanwp/oceanwp#209]
I'm pretty sure the hook plugin broke with a recent update.  Old hooks remain working, but new ones won't work.

**Comment by GamingGav** [comment]
Okay, I did some debugging and found what's causing my issue.  You can't make a hook in Elementor with just a background image, also a space divider won't solve the issue either. Can this be fixed so I can do so? I don't want to put an image or text inside this div hook.

**Comment by AlexdeBorba** [comment]
Hello @GamingGav 

As far as we are aware, Ocean Hooks is working well, without issues.

Have you tried to save it as a template and use the shortcode it generates as a Hook?

**Comment by AlexdeBorba** [comment]
@GamingGav, can you update us on this?

**Comment by GamingGav** [comment]
@AlexdeBorba Will do later today.

**Comment by GamingGav** [comment]
@AlexdeBorba I tested this issue again today, and it seems to have been fixed since I originally reported it. Which is great news, since I've been switiching back to OceanWP from Astra, after going to Astra when this bug was happening to me.

**Comment by AlexdeBorba** [comment]
@GamingGav, thank you for updating us, and I will consider this closed.

**Comment by hirenshah** [comment]
I think there is something still wrong with the hooks plugin.  I've been trying to set a slider to appear after the header, one for the homepage and one for everywhere else.

I created a template for each, and set up the hook conditions for the homepage.  That worked perfectly.  Then I did the same with the other template, but this time for all pages which are not the homepage. 

The second one worked, but then stopped the homepage one working.  I thought there may be an issue with the priorities, so I varied them a little but had no luck.  

I can't seem to get any output most of the time either when trying other hook locations... I have no idea what I am doing wrong though.

**Comment by hirenshah** [comment]
Definitely something wrong... I added my template shortcode:
`[oceanwp_library id="10070"]`

Under "_Before Content Inner_" in the deprecated settings and the content immediately appeared on the pages.

If I remove that and try and do it via the Hooks section of that template, I get no output again.

**Comment by hirenshah** [comment]
@AlexdeBorba 

I have resorted to using a code snippets plugin / functions.php to basically do what this plugin was meant to do.

I had mentioned earlier that setting up another instance of the same hook broke the first one... well this time creating a before content one, stopped the after header one working.

As mentioned, doing all this things via the deprecated page or using code, works flawlessly.
